#+STARTUP: showall
2016-12-30_10:08:22_-0800_PST
* "Things" Bias - Accounting for reality
I was dropping off my girlfriend at the mall yesterday. I decided that
when I got back home I would go into a long coding session. I was in
traffic, and Waze showed 11 minutes from my go-to pizza
place. Pizza... Unhealthy, pre-cooked, and quickly rewarmed. A
hacker's dream. I called ahead, ordered, picked it up, and on the
drive back I was thinking about something I read in /Rationality: From
AI to Zombies/ by Eliezer Yudkowsky.

This book talks about /bias/, and it really struck a chord with me to
entertain Yudkowsky's ideas seriously. I liked how he attempted to
define bias from a higher level of abstraction.

I treat biases very seriously. I thought: what about biases that we
are unaware of? Could we systematically and exhaustively eliminate or
correct for them?

I tried to come up with a random bias. What I came up with is, can we
be biased just by having the things we have? Take, for example, my
car. I entertained what would happen if I *didn't* have a car.

I had run out of bread in the house and this was also on my mind. How
would I deal with this? Instead of going to Costco and getting my food
at wholesale prices, I could go to the store which is walking distance
and is also going to overcharge for every item. Would I adapt? Would
I, say, find an alternative method of getting bread into the house?

I think the reason I wanted to write this blog post is this: Could
having "things" affect the way we view the world?

I think that we could be biased by the very objects that surround us,
and by what we have. We could be biased by the reality that we live
in. And we need to account for that.
