#+STARTUP: showall

2016-12-26_00:25:07_-0800_PST
* To Serif or Not to Serif [working title]

I've had an obsession with creating the best website I could
for quite a while now.
As someone who started programming with C though,
I've always thought of myself as a low-level,
/back-end/ developer first.

Front-end was scary.
I had no idea how to make a great website.
For some reason,
my analytical mind told me that
there is no way I could leverage rules,
with art.

Rules ruin art.
Surely, there is no way
I can create a beautiful website
with a logical, cold, calculating mind.
At least that's what my subconscious was telling me.

Looking back,
my love for accessibility seems natural.
When I discovered I could get a score on my website,
it was on.
Metrics was exactly what the doctor ordered.

My mental breaks consisted of going on [[http://colorsafe.co][colorsafe.co]]
and trying out different combinations of color shades
to find that perfect balance of WCAG acceptance and style.

I've found there was something lacking.
Unhappy not to get the perfect result,
I decided to get more /specific/.

I started to pay close attention
to how fonts play a role
in the readability of website content.

Every time I opened a website that I thought was readable,
I would note the layout, colors, and what kind of fonts were used.
Specifically, I would note the size of the font, the color,
and the font-family.
My previously clean desktop became littered
with screenshots of various websites,
with the web inspector capturing the font details.

As I accidentally discovered,
/sans/ Serif fonts tend to be more readable at smaller font sizes,
than fonts with Serif.

My second thought was to immediately try out
a few of the most popular Sans-Serif fonts.
I opened up the Atom editor,
manually cycled the font-family attribute
on the CSS stylesheet for my website,
and, based on a quick overview
of what each font looked like,
I settled on Verdana as the most readable.

Having Verdana on my site was great.
I had maximized the readability
of the font on my website.

In the back of my mind,
there was always this nagging feeling though,
that my work was not yet done.

Yes, I had achieved readability,
but now I needed to add some salt and pepper.

Today, I discovered a new font.

In my habit of inspecting the CSS rules on different websites,
I was inspired by an interesting article [1]
I randomly stumbled upon,
which used Andada.
What is Andada, you ask?

Google has openly released
a beautiful set of fonts [2] that
anyone can use, for free.
Though a Serif font,
Andada felt surprisingly readable to me,
almost striking that perfect balance
of readability and "pizzaz."
As a test,
I've decided to style the content
of this blog post
in this new font,
and see how I liked it.

Happy holidays, and, enjoy Serif!

** Post Scriptum

When switching over
to a Serif font,
I noticed I had to make the font bigger
in order to achieve consistency
with the other posts.
Verdana in 16 px became 18px in 'Andada'.

[1] http://rhodesmill.org/brandon/2012/one-sentence-per-line/ by
Brandon Rhodes ([[https://news.ycombinator.com/item?id%3D4642395][HN]])

[2] https://fonts.google.com
