#+STARTUP: showall
2016-12-30_10:08:22_-0800_PST
* Things Bias - Correcting for Reality [working title]
I was dropping off my girlfriend at the mall yesterday, and decided to
go into a long coding session as soon as I got home. I was in traffic,
11 minutes from my go-to pizza place. Unhealthy, pre-cooked, and
quickly rewarmed. A hacker's dream. I called ahead, ordered, and on
the drive back I was thinking about something I read in /Rationality:
From AI to Zombies/.

This book talks about Bias, and it really struck a chord with me to
entertain Yudkowsky's ideas seriously. I liked how he attempted to
define bias from a higher level of abstraction.

For some reason that I can't understand, I thought of a new kind of
bias that I hadn't ever thought of before.

I call it the "Things" bias. And I was just thinking, "hey, what would
I be doing if I didn't have a car and I wanted pizza?" First thing
that came to my mind was, oh I'd order it. But hell no. No way in hell
am I ordering it.

When I came to San Francisco, I worked as a delivery guy for
OrderAhead. I did it for about a month and a half. The money didn't
make any sense. One of my tire's blew out: $300 repair. Then I got two
parking tickets, which are the result of the meter maids not liking
you to run in to deliver some food (Why is that? I thought I was
providing a service to the residents of the city.)

I didn't like it. I'm not having anyone else go through that shit. If
I want a pizza, I go and get it, instead of exploit some poor guy who
doesn't know he's making less than minimum wage. I'd thought this
before every time I ordered on Yelp, and being a delivery guy myself
just confirmed it.

So what would I do if I didn't have a car?

I still don't know what I would have done. Most likely, I would have
had to walk somewhere to get food, since I ran out of bread and I
can't make a sandwich.

My takeaway is this: I want to know what would happen if I *didn't*
use my car. So for the next two weeks, I'm going to try to see what
would happen if I got bread from the only store in walking distance
that rips you off. Would I be getting ripped off?

But more importantly, my work isn't done. What kinds of other "things"
biases could I have?

--THE END--
