#+STARTUP: showall
2016-12-30_10:08:22_-0800_PST
* Things Bias - Correcting for Reality [working title]
I was dropping off my girlfriend at the mall yesterday, and decided to
go into a long coding session as soon as I got home. I was in traffic,
and Waze showed 11 minutes from my go-to pizza place. Unhealthy,
pre-cooked, and quickly rewarmed. A hacker's dream. I called ahead,
ordered, picked it up, and on the drive back I was thinking about
something I read in /Rationality: From AI to Zombies/.

This book talks about /bias/, and it really struck a chord with me to
entertain Yudkowsky's ideas seriously. I liked how he attempted to
define bias from a higher level of abstraction.

I treat biases very seriously. I thought: what about biases that we
are unaware of? Could we systematically and exhaustively eliminate or
correct for them.

I had run out of bread in the house and this was also on my mind. I
could either go to Costco.

What would I do if I didn't have a car?

My takeaway is this: I want to know what would happen if I *didn't*
use my car. So for the next two weeks, I'm going to try to see what
would happen if I got bread from the only store in walking distance
that rips you off. Would I be getting ripped off?

But more importantly, my work isn't done. What kinds of other "things"
biases could I have?

--THE END--
