<!DOCTYPE html>
<html lang="en">
  <head>
<?php
    include 'head.phtml';
?>
  </head>

  <body>
<?php
    include 'nav.phtml';
?>
    <div class="container">
      <div class="blog-header">

      </div>

      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="postit-img-container">
					  <div class="img-container">
					    <img id="backdrop" src="holbertonbackdrop.gif" alt="Holberton Background Image">
					  </div><!-- /.img-container -->
            <div class="postit">
              <h3>
                <a href="https://github.com/dalzuga?tab=repositories">
                  Daniel's Repositories
                </a>
              </h2>
            </div>
					</div>
          <div class="blog-post">
            &nbsp;
            <h2 class="blog-post-title">Projects</h2>
            &nbsp;
            <ul>
              <li>
                <a href="https://github.com/dalzuga/simple_shell">Simple Shell</a> - This is a UNIX-based shell written in C.
              </li>
              <li>
                <a href="https://github.com/dalzuga/dalzuga.github.io">dalzuga.github.io</a> - This is this website's repository.
              </li>
            </ul>
          </div>
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
<?php
          include 'sidebar.phtml';
?>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="sticky">Currently in BETA</div>

<?php
    // include 'footer.phtml';
?>

<?php
  include 'scripts.phtml';
?>
  </body>
</html>
