<!DOCTYPE html>
<html lang="en">
  <head>
<?php
    include 'head.phtml';
?>
  </head>

  <body>
<?php
    include 'nav.phtml';
?>
    <div class="container">
      <div class="blog-header">
        <h1 class="blog-title">The Hippokampos</h1>
        <p class="lead blog-description">From the Greek ἱππόκαμπος, "seahorse" from ἵππος hippos, "horse" and κάμπος kampos, "sea monster."</p>
      </div>

      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="postit-img-container">
					  <div class="img-container">
					    <img id="backdrop" src="holbertonbackdrop.gif" alt="Holberton Background Image">
					  </div><!-- /.img-container -->
            <div class="postit">
              <h3>
                <a href="https://github.com/dalzuga?tab=repositories">
                  Github Repository List
                </a>
              </h2>
            </div>
					</div>
          <div class="blog-post">
            <h2 class="blog-post-title">Project Repositories</h2>
            &nbsp;
            <ul>
              <li>
                <a href="https://github.com/dalzuga/simple_shell">Simple Shell</a> - This is a C project with <a href="https://github.com/bennettbuchanan/simple_shell">Bennett Buchanan</a>.
              </li>
              <li>
                <a href="https://github.com/dalzuga/dalzuga.github.io">dalzuga.github.io</a> - This is this website's repository.
              </li>
            </ul>
          </div>
          <div class="blog-post">
            <h2 class="blog-post-title">Git Resources FAQ</h2>
            &nbsp;
            <ul>
              <li>
                <h3>How to revert a commit for just one file</h3>
                 <p><code>git revert</code> will not handle this. You have to use <code>git checkout</code> to target a specific file. <code>git checkout</code> lets you retrieve a file in the past.</p>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="http://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git">Reset or revert a specific file to a specific revision using Git? - Stack Overflow</a>.</li>
                </ul>
              </li>
            </ul>
          </div>
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
<?php
          include 'sidebar.phtml';
?>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="sticky">Currently in BETA</div>

<?php
    include 'footer.phtml';
?>

<?php
  include 'scripts.phtml';
?>
  </body>
</html>
