<!DOCTYPE html>
<html lang="en">
  <head>
<?php
    include 'head.phtml';
?>
  </head>

  <body>
<?php
    include 'nav.phtml';
?>
    <div class="container">
      <div class="blog-header">

      </div>

      <div class="row">
        <div class="col-sm-8">
<?php
          include 'progress.phtml';
?>
        </div><!-- /.blog-main -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="sticky">Currently in BETA</div>

<?php
  include 'scripts.phtml';
?>
  </body>
</html>
