<!DOCTYPE html>
<html lang="en">
  <head>
<?php
    include 'head.phtml';
?>
  </head>

  <body>
<?php
    include 'nav.phtml';
?>
    <div class="container">
      <div class="blog-header">

      </div>

      <div class="row">
        <div class="col-sm-8">
          <div class="postit-img-container">
            <div class="img-container">
              <img id="backdrop" src="holbertonbackdrop.gif" alt="Holberton Background Image">
            </div><!-- /.img-container -->
            <div class="postit">
              <h3>
                <a href="https://docs.google.com/a/holbertonschool.com/document/d/1Ey6E3T1p68gb_ptxot6BU0PbODc62tvGevUJeSYQWGg/edit?usp=sharing">
                  A/V Checklist</a>
                  |&nbsp;
                <a href="https://docs.google.com/a/holbertonschool.com/document/d/16asLirLdW0z0MQ7-48WWBX5ADy9oUFNOyiZBJodpgvs/edit?usp=sharing">
                  A/V Troubleshooting</a>
              </h3>
            </div>
          </div>
<?php
          include 'progress.phtml';
?>
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
<?php
          include 'sidebar.phtml';
?>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="sticky">Currently in BETA</div>

<?php
  include 'scripts.phtml';
?>
  </body>
</html>
