    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item<?php $this->nav_active("index.html") ?>" href="index.html">Home</a>
          <a class="blog-nav-item<?php $this->nav_active("blog.html") ?>" href="blog.html">Blog</a>
          <a class="blog-nav-item<?php $this->nav_active("github.html") ?>" href="github.html">Github</a>
          <a class="blog-nav-item<?php $this->nav_active("ref.html") ?>" href="ref.html">Reference</a>
          <a class="blog-nav-item<?php $this->nav_active("calendar.html") ?>" href="calendar.html">Calendar</a>
          <div role="presentation" class="dropdown">
            <a class="dropdown-toggle blog-nav-item" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Front-end Projects <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="level2/">Level 2</a></li>
              <li><a href="http://158.69.92.190/loginform.php">Simple Twitter</a></li>
              <li><a href="discover-bootstrap/">Discover Bootstrap</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="twitter-clone/">Twitter Clone Project</a></li>
            </ul>
          </div>
        </nav>
      </div>
    </div>
