<?php $progress = $this->progress ?>
          <div class="clearfix visible-lg-block visible-md-block visible-sm-block visible-xs-block"></div>
          <div class="blog-post">
            <h2 class="blog-post-title">Under Construction... <img id="construction-image" src="under_construction.png" alt="Under construction"></h2>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $progress ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $progress ?>%;">
                <?php echo $progress ?>%
              </div>
            </div>
            <label for="progress-bar">Track my progress <a href="https://github.com/dalzuga/dalzuga.github.io">here.</a> You can check the wireframe <a href="wireframe.png">here.</a></label>
          </div>
