<!DOCTYPE html>
<html lang="en">
  <head>
<?php
    include 'head.phtml';
?>
  </head>

  <body>
<?php
    include 'nav.phtml';
?>
    <div class="container">
      <div class="blog-header">

      </div>

      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
            <h2 class="blog-post-title">Git</h2>
            <ul>
              <li>
                <h3>How to revert a commit for just one file</h3>
                 <p><code>git revert</code> will not handle this. You have to use <code>git checkout</code> to target a specific file. <code>git checkout</code> lets you retrieve a file in the past.</p>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="http://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git">Reset or revert a specific file to a specific revision using Git? - Stack Overflow</a>.</li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="blog-post">
            <h2 class="blog-post-title">C</h2>
            <ul>
              <li>
                <h3>Makefile</h3>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="http://mrbook.org/blog/tutorials/make/">Makefiles &#8211; Mrbook&#039;s Stuff</a></li>
                </ul>
              </li>
              <li>
                <h3>Hash table</h3>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="https://www.youtube.com/watch?v=MfhjkfocRR0">What is a HashTable Data Structure - Introduction to Hash Tables , Part 0 - YouTube</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="blog-post">
            <h2 class="blog-post-title">Bash</h2>
            <ul>
              <li>
                <h3>How to search for a file using Bash</h3>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="http://www.tldp.org/LDP/abs/html/moreadv.html">Complex Commands</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="blog-post">
            <h2 class="blog-post-title">MySQL</h2>
            <ul>
              <li>
                <h3>How to get a list of MySQL user accounts</h3>
                <code>select User,Host from mysql.user;</code>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="http://stackoverflow.com/questions/1135245/how-to-get-a-list-of-mysql-user-accounts">mysql5 - How to get a list of MySQL user accounts - Stack Overflow</a></li>
                </ul>
              </li>
              <li>
                <h3>How change character set of a database</h3>
                <code>ALTER DATABASE databasename CHARACTER SET utf8 COLLATE utf8_general_ci;</code>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="http://stackoverflow.com/questions/22572558/how-to-set-character-set-database-and-collation-database-to-utf8-in-my-ini">mysql5 - How to set character_set_database and collation_database to utf8 in my.ini? - Stack Overflow</a></li>
                </ul>
              </li>
              <li>
                <h3>How to delete all tables and users</h3>
                <p>
                  To delete all users:<br>
                  <code><?php echo htmlspecialchars("mysql -uroot -p -e \"select User from mysql.user;\" | grep -v User | grep -v root | grep -v debian-sys-maint | gawk '{print \"drop user \" $1\";select sleep(0.1);\"}' > droppedusers.sql && cat droppedusers.sql")?></code>
                </p>
                <p>
                  After deleting users:
                  <code>FLUSH PRIVILEGES;</code>
                </p>
                <p>
                  To delete all tables:<br>
                  <code><?php echo htmlspecialchars("mysql -uroot -p  -e \"show databases\" | grep -v Database | grep -v mysql | grep -v information_schema | gawk '{print \"drop database \" $1\";select sleep(0.1);\"}' > droppeddatabases.sql && cat droppeddatabases.sql")?></code>
                </p>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="https://rootedlabs.wordpress.com/2009/10/03/drop-all-databases-in-mysql/">Drop All Databases in MySQL | Mohinish&#039;s Blog</a></li>
                </ul>
              </li>
              <li>
                <h3>ERROR 1396 (HY000): Operation DROP USER failed</h3>

                <code>FLUSH PRIVILEGES;</code>
                 <p>Reference:</p>
                 <ul>
                   <li><a href="http://stackoverflow.com/questions/20698335/error-1396-hy000-operation-drop-user-failed-for-userlocalhost">mysql5 - ERROR 1396 (HY000): Operation DROP USER failed for 'user'@'localhost' - Stack Overflow - Stack Overflow</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
<?php
          include 'sidebar.phtml';
?>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <div class="sticky">Currently in BETA</div>

<?php
    include 'footer.phtml';
?>

<?php
  include 'scripts.phtml';
?>
  </body>
</html>
